### ISSUE TITLE
Constructing the mirror, deploying the magic mirror framework to raspberry pi and initializing the mirror with default modules.

### ISSUE THREAD

**Issue by BurakDmb** [ETU-ABC/ABC-Mirror#9]

**Comment by cemalkilic** [comment]
"Magic Mirror" platform will be used as our base system. The platform is configured & tested first on Raspberry Pi 3 Model B+. After that, for testing purposes it is tested on Ubuntu 16.04 and is working. Further customization will be made via modules.
The issue is closed since the initialization step is completed.
